livepeer/stream-tester

- cmd/streamtester/streamtester.go
- internal/model/models.go
- internal/server/server.go
- internal/testers/streamer.go
Currently, stream-tester assumes that the broadcaster and orchestrator nodes are hosted on the same machine.  It takes a "host" string argument along with "rtmp" & "media" integer arguments that designate the ports to be used on the single host.
This adds a new field for the media / orchestrator host name to be used in addition to the existing field that is used for the rtmp / broadcaster host name.
This was done in a fully-backward compatible way - If the new field is not provided, the application will continue to function with its original behavior.
blocks https://github.com/livepeer/livepeer-infra/issues/32
closes https://github.com/livepeer/stream-tester/issues/14
> Add the ability to specify separate rtmp & media (B & O) hosts

- cmd/streamtester/streamtester.go
this allows me to store the stats after a stream-test run in a json file to be compared later in the droneCI pipeline
fixes https://github.com/livepeer/livepeer-infra/issues/74
> adding `stats-file` flag

- .gitignore
- Dockerfile
- Makefile
- cmd/stream-monitor/stream-monitor.go
- cmd/streamtester/streamtester.go
- docker-compose.yml
- internal/server/metrics.go
- internal/testers/http_load_tester.go
- internal/testers/http_streamer.go
Stream a target file to http ingest in cycles and surface metrics on these stream-cycles via a prom exporter.
> Add stream-monitor binary

- cmd/mist-api-connector/mist-api-connector.go
- internal/app/mistapiconnector/mistapiconnector_app.go
`record` is a sensible default, but I needed just now to record a stream with no audio, and maybe someday we want to always send audio without recording for some reason.
> mist-api-connector: add -send-audio=always/never/record

- Dockerfile.load-test
- cmd/mist-api-connector/mist-api-connector.go
- internal/app/mistapiconnector/mistapiconnector_app.go
Instead of hitting a service, we can create our own custom service record and forward traffic wherever we want. So this sets us up to route `/hls/{playbackId}` to `https://mdw-staging-mist-server-0.livepeer.monster`, which is ready for global replication on ingest URLs.
> change consul parameters

- cmd/orch-tester/orch_tester.go
- internal/testers/azure.go
- internal/testers/m3utester2.go
- internal/testers/mediadownloader.go
If enabled using `-randomsample=true` orch-tester will randomly sample a segment and write it to the provided GCP bucket (`-gsbucket` and  `- gskey`) 
1. For each orchestrator pick a random video profile and seqNo 
2. Start the stream 
3. As the stream is started start fetching the target segment from the broadcaster
4. When the stream finishes stop fetching segments from the broadcaster
5. If no segment is found query the entire last known playlist for the stream's manifest ID
6. from that playlist randomly get a segment
> orch-tester: random sample segments

- Dockerfile
Add an HLS playlist with uniform 2s segments (the last segment is shorter) to the Docker container root directory.
The playlist was generated with the following command:
```bash
ffmpeg -i official_test_source_2s_keys_24pfs_30s.mp4 -c:a copy -c:v libx264 -x264opts "keyint=48:min-keyint=48:no-scenecut" -f hls -hls_time 2 -hls_playlist_type vod hls/bbb.m3u8
```
See livepeer/livepeer-infra#326
> Dockerfile: Add HLS playlist video asset

- cmd/mist-api-connector/mist-api-connector.go
- internal/app/mistapiconnector/mistapiconnector_app.go
Changes necessary for global playback URL — need the location prefixes on there so we can tell the difference between different datacenters, and need the regex to respond to both `{region}-playback-{secret}.livepeer.monster` and `playback-{secret}.livepeer.monster`.
> mist-api-connector: add -consul-prefix, regex host

- internal/app/mistapiconnector/mistapiconnector_app.go
When I ask Mist to return absolute URLs, it returns them like this: 
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:8
#EXT-X-MEDIA-SEQUENCE:7
#EXTINF:6.333000,
https://mdw-cdn.livepeer.monster/hls/video+9e60a32fv9h42mvd/4_1/27067_33400.ts
#EXTINF:6.000000,
https://mdw-cdn.livepeer.monster/hls/video+9e60a32fv9h42mvd/4_1/33400_39400.ts
#EXTINF:6.334000,
https://mdw-cdn.livepeer.monster/hls/video+9e60a32fv9h42mvd/4_1/39400_45734.ts
#EXTINF:6.000000,
https://mdw-cdn.livepeer.monster/hls/video+9e60a32fv9h42mvd/4_1/45734_51734.ts
#EXTINF:6.333000,
https://mdw-cdn.livepeer.monster/hls/video+9e60a32fv9h42mvd/4_1/51734_58067.ts
#EXTINF:5.733000,
https://mdw-cdn.livepeer.monster/hls/video+9e60a32fv9h42mvd/4_1/58067_63800.ts
#EXTINF:5.634000, …
```
> mist-api-connector: route traffic with 'video+' correctly

- cmd/loadtester/loadtester.go
Useful if the test is failing and I want to leave it running while I figure out why.
> loadtester: add -wait-for-target=30s

- internal/app/mistapiconnector/mistapiconnector_app.go
This is a proposal for the `etcd` write failure we are still getting once and a while in production.
I believe it will be necessary even after we change the `etcd` endpoints to contain all members of 
the cluster, since `mist-api-connector` itself is already using the `AutoSyncInterval` option of
the client, which means that it will only stay attached to a single server on the first 5 minutes 
after startup. After that, the client will grab all endpoints from the cluster automatically.
So we are still losing the session sometimes for some reason, and I believe having a recovering
mechanism like this will fix any issues from that. Also added a last resort mechanic of shutting 
down the server in case we can't recover the session after 2 minutes, which feels like a time we
would be …
> mist-api-connector: Recover etcd session when lease is lost

- cmd/mist-api-connector/mist-api-connector.go
- internal/app/mistapiconnector/mistapiconnector_app.go
This is first to implement a healthcheck API in mapic server, to allow creating a readiness probe in k8s.
On the way to that also found out that we have frequent restarts (up to 2) on `mist-api-connector` because
it tries to connect too fast to Mist, before it is ready. So I implemented a little retry logic on startup so we 
give some time for Mist server to be available before giving up and restarting the container.
Some idea I had for the future is being able to configure mapic containers with a `restartPolicy: never`, so
we can make sure that the mapic container never restarts. Those would create inconsistencies between its
state in etcd/memory with what is actually happening on mist side, so we probably want some datadog alerts
in case any of those happen (either mist or mapic)
> mist-api-connector: Implement healthcheck for k8s probes

- internal/app/mistapiconnector/mistapiconnector_app.go
Do so by calling GetConfig API which felt lightweight enough
to be called frequently (every ~5s or so)
> mist-api-connector: Check mist-api on healthcheck

- apis/livepeer/livepeer.go
- internal/app/mistapiconnector/mistapiconnector_app.go
Following the [rename on the API](https://github.com/livepeer/livepeer-com/pull/557), this does the same renames
on the current only known client for the feature.
> mist-api-connector: Rename (rtmp)push(target) to multistream(target)

- internal/app/mistapiconnector/mistapiconnector_app.go
Broken because it didn't have the right prefix. But a small change gets it working again.
Verified working in `livepeer-in-a-box`.
> mist-api-connector: fix deleteEtcdKeys

- .github/workflows/dockerimage.yml
- .github/workflows/go.yml
- .github/workflows/load-tester-dockerimage.yml
- .github/workflows/mist-api-connector-dockerimage.yml
- .github/workflows/record-tester-dockerimage.yml
Following up on https://github.com/livepeer/livepeer-infra/pull/686, we would like to have some version tags
in all of our repos. This is the first repo after `livepeer-data` being updated to this new format.
Differently from `livepeer-data`, I haven't really repeated [the whole logic](https://github.com/livepeer/livepeer-data/compare/v0.2.1...v0.2.4#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R3) of grabbing the containing
branch for a tag build, nor have I enabled `tag` event builds for our docker images (only the release workflow
is actually run on those).
I will try to create a github action that extracts all the raw tags that we want to publish for a given image to
avoid repating that script everywhere else.
> CI: Publish version tags with all images

- apis/livepeer/livepeer.go
- internal/app/mistapiconnector/mistapiconnector_app.go
This is to add a couple retries to the `/setactive` call to the API, to hopefully diminish the inconsistencies
we observe on some streams that are actually active but the state on the database say they are not.
Also added a log that we should create an alert on.
> mist-api-connector: Add retries to `/setactive` request

- .github/workflows/dockerimage.yml
- .github/workflows/load-tester-dockerimage.yml
- .github/workflows/mist-api-connector-dockerimage.yml
- .github/workflows/record-tester-dockerimage.yml
Use the `always-latest-on-branch` input to the gh action (created [here](https://github.com/livepeer/action-gh-release-tags/commit/1442c82d03ecfc7adf61e5c4c8c796bda167812b))
so we only publish `latest` tags on the specified branches.
While `latest` will only be pushed on those branches, we can still test the
generated images from any branch since I removed the action filter to only
run on master/mist-api-connector branch.
Also thinking if I should get rid of the `mist-api-connector` branch. Will
create a discussion inline.
> .github/ci: Build images on every branch

- internal/app/mistapiconnector/mistapiconnector_app.go
- internal/app/mistapiconnector/stats_collector.go
- internal/metrics/census.go
They will be globally aggregated on Victoria Metrics and retained for at least 30 days, so
that we can create with a view for the total number of multistreamed minutes (and bytes)
per month.
This implements https://github.com/livepeer/livepeer-com/issues/675
> mist-api-connector: Export metrics for multistream usage minutes/bytes

- Makefile
Idea came from https://github.com/livepeer/livepeer-infra/pull/738#issuecomment-988345269 to make the release process a little easier.
> make: Create `make release` command to tag and update `mapic-release` branch

- .github/workflows/go.yml
- .gitignore
- Makefile
Creates a naming pattern as defined by #127.
PS: The list of files specified with `files:|` seems too detailed. Should be a wildcard method to achieve the same.
> Follow consistent naming for all release artifacts

- internal/app/mistapiconnector/stats_collector.go
- internal/metrics/census.go
* This change adds streamID tags to the `multistream_usage_megabytes` `multistream_usage_minutes` metrics of mist-api-connector service
Testing:
compiles with `make connector`
Issue:
https://app.zenhub.com/workspaces/video-user-team-5dd2c75e4ee08500015994d7/issues/livepeer/go-livepeer/2172
> feature: mist-api-connector tags per-stream metrics

- cmd/recordtester/recordtester.go
- internal/app/recordtester/continuous_record_tester.go
- internal/app/recordtester/recordtester_app.go
- messenger/messenger.go
That API now returns the global ingest and we don't want that.
We should instead stream into the region being tested and so
the best way for that should be receiving an explicit argument
instead, since we don't want to expose the regional URLs in any
way to our users.
> recordtester: Add ingest arg to skip LP /api/ingest
